
package com.fusesource.training;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-10T08:33:15.637+05:30
 * Generated source version: 3.4.2
 */

@WebFault(name = "NoSuchCustomer", targetNamespace = "http://training.fusesource.com/")
public class NoSuchCustomerException extends Exception {

    private com.fusesource.training.NoSuchCustomer faultInfo;

    public NoSuchCustomerException() {
        super();
    }

    public NoSuchCustomerException(String message) {
        super(message);
    }

    public NoSuchCustomerException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public NoSuchCustomerException(String message, com.fusesource.training.NoSuchCustomer noSuchCustomer) {
        super(message);
        this.faultInfo = noSuchCustomer;
    }

    public NoSuchCustomerException(String message, com.fusesource.training.NoSuchCustomer noSuchCustomer, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = noSuchCustomer;
    }

    public com.fusesource.training.NoSuchCustomer getFaultInfo() {
        return this.faultInfo;
    }
}
