spring:
  h2:
    console:
      enabled: true
      
management:  endpoints:    web:      exposure:        include:        - "*"
        
  endpoint:    shutdown:      enabled: true
            
      